<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.29.2" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.24" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Afrimine.Model\Afrimine.Model.csproj" />
    <ProjectReference Include="..\Afrimine.Repository\Afrimine.Repository.csproj" />
    <ProjectReference Include="..\src\Afrimine.Shared\Afrimine.Shared.csproj" />
	  <PackageReference Include="Google.Apis.Auth" Version="1.68.0" />
  </ItemGroup>

</Project>
